title: Shreyan Chowdhury
logo: /assets/img/dp.jpg
description: music tech researcher, uses machine learning to understand audio
show_downloads: false
google_analytics: UA-144561544-1
theme: jekyll-theme-minimal
