title: Shreyan Chowdhury
#logo: /assets/img/dp2.jpg
description: machine learning + music
show_downloads: false
google_analytics: UA-144561544-1
theme: jekyll-theme-minimal

social_links:
    twitter: shreyan_ch
    scholar: my_profile
    linkedin: shreyan-chowdhury
    soudncloud: shreyan-chowdhury